- hosts: localhost
  tags:
    - spawn
  roles:
    - role: local_ssh_key
    - role: gogs_terraform
    - role: wait_ssh_connect
      group_name: 'gogs'

- hosts: gogs
  roles:
    - role: rds_password
    - role: docker
    - role: gogs_ssh_host_keys
    - role: gogs_docker_conf_import
    - role: gogs_docker_rds
    - role: gogs_letsencrypt
    - role: gogs_docker_proxy_nginx

- hosts: gogs
  gather_facts: False
  roles:
    - role: gogs_docker
    - role: nginx
