
- assert:
    that:
       - 'gogs_secret_key is defined'

- name: 'Export gogs_config'
  set_fact:
    gogs_config: >-
      {%- if gogs_domain is defined -%}
        {%- set _ = gogs_config['server'].update({
            'DOMAIN': gogs_domain,
            'SSH_DOMAIN': gogs_ssh_domain|default(gogs_domain),
            'ROOT_URL': 'https://' ~ gogs_domain ~ '/'
        }) -%}
      {%- endif -%}
      {{ gogs_config }}

- name: 'create local conf dir'
  file:
    dest: '{{ gogs_local_conf | dirname }}'
    state: directory
