debug: False

gogs_acme_dir: /var/lib/gogs/acme/

acme_staging_url: acme-staging.api.letsencrypt.org
acme_prod_url: acme-v01.api.letsencrypt.org

acme_staging: False

acme_url: '{{ acme_staging|ternary(acme_staging_url, acme_prod_url) }}'
