- name: 'install python binding for docker'
  package:
    name: >-
      {%- if ansible_python.version.major == 3 -%}
         ['python3-docker']
      {%- else -%}
         ['python-docker']
      {%- endif -%}
    state: present

- name: 'get facts about current container'
  docker_container:
    name: gitea
    image: '{{ gitea_image }}:{{ gitea_version }}'
  register: docker_gitea_facts
  check_mode: True
  changed_when: False

- debug:
    var: docker_gitea_facts
  when: debug|bool

- name: 'Get current docker env_vars (if started)'
  set_fact:
    current_env_vars: >-
        {%- set current_env_vars = {} -%}
        {%- for env_var in (((docker_gitea_facts.ansible_facts|default).docker_container|default).Config|default).Env|default([]) -%}
              {%- set name, value = env_var.split('=', 1) -%}
              {%- set _ = current_env_vars.update({name: value}) -%}
        {%- endfor -%}
        {{ current_env_vars }}

- debug:
    var: current_env_vars
  when: debug|bool

- name: 'Search for gitea stateless password'
  set_fact:
    _gitea_db_password: >-
        {%- if gitea_db_password is defined -%}
            {{ gitea_db_password }}
        {%- else -%}
            {%- set _gitea_db_password = play_hosts|map('extract', hostvars,
                    ['current_env_vars', 'GITEA_DB_PASSWORD'])|select|list -%}
            {%- if _gitea_db_password|length > 0 -%}
                {{ _gitea_db_password|first }}
            {%- else -%}
                {{ lookup('password', '/dev/null') }}
            {%- endif -%}
        {%- endif -%}

- debug:
    var: _gitea_db_password
  when: debug|bool
