
- assert:
    that:
       - 'gitea_secret_key is defined'

- name: 'Export gitea_config'
  set_fact:
    gitea_config: '{{ gitea_config }}'

- name: 'create local conf dir'
  file:
    dest: '{{ gitea_local_conf | dirname }}'
    state: directory
