
- name: 'Search for gitea stateless password'
  set_fact:
    gitea_db_password: >-
      {%- set gitea_db_password_list = play_hosts|map('extract', hostvars,
              ['gitea_config', '', 'PASSWD'])|select|list -%}
      {%- if gitea_db_password_list|length > 0 -%}
          {{ gitea_db_password_list|first }}
      {%- else -%}
          {{ lookup('password', '/dev/null') }}
      {%- endif -%}
  when: gitea_db_password is undefined

- name: 'template gitea conf'
  template:
    src: app.ini.j2
    dest: '{{ gitea_local_conf }}'
  register: gitea_conf_file

- name: 'install python binding for docker'
  package:
    name: >-
      {%- if ansible_python.version.major == 3 -%}
         ['python3-docker']
      {%- else -%}
         ['python-docker']
      {%- endif -%}

- name: 'compute fact'
  set_fact:
    gitea_force_restart: True

- name: 'start gittea container'
  docker_container:
    name: gitea
    image: '{{ gitea_image }}:{{ gitea_version }}'
    published_ports:
      - '80:3000'
      - '2222:22'
    volumes:
      - '{{ gitea_local_dir }}:/data/gitea'
    restart_policy: 'unless-stopped'
    restart: '{{ gitea_force_restart }}'
