- name: 'install python binding for mariadb'
  package:
    name: >-
      {%- if ansible_python.version.major == 3 -%}
         ['python3-mysqldb']
      {%- else -%}
         ['python-mysqldb']
      {%- endif -%}
    state: present

- name: 'Search for gogs stateless password'
  set_fact:
    gogs_db_password: >-
      {%- set gogs_db_password_list = play_hosts|map('extract', hostvars,
              ['gogs_config', 'database', 'PASSWD'])|select|list -%}
      {%- if gogs_db_password_list|length > 0 -%}
          {{ gogs_db_password_list|first }}
      {%- else -%}
          {{ lookup('password', '/dev/null') }}
      {%- endif -%}
  when: gogs_db_password is undefined

- debug:
    var: gogs_db_password
  when: debug|bool

- name: 'update gogs config'
  set_fact:
    gogs_config: >-
      {%- set database_dict = gogs_config.setdefault('database', {}) -%}
      {%- set _ = database_dict.update({
        'DB_TYPE': 'mysql',
        'HOST': gogs_mariadb.instance.endpoint ~ ':3306',
        'USER': gogs_db_username,
        'PASSWD': gogs_db_password,
        'NAME': gogs_db_name,
      }) -%}
      {{ gogs_config }}

- debug:
    var: gogs_config
  when: debug|bool

- name: 'create gogs password for mariadb'
  mysql_user:
    login_host: '{{ gogs_mariadb.instance.endpoint }}'
    login_user: '{{ db_username }}'
    login_password: '{{ db_password }}'
    host: '%'
    name: '{{ gogs_db_username }}'
    password: '{{ gogs_config.database.PASSWD }}'
    priv: 'gogs.*:ALL,GRANT'
