- name: 'install python binding for mariadb'
  package:
    name: >-
      {%- if ansible_python.version.major == 3 -%}
         ['python3-mysqldb']
      {%- else -%}
         ['python-mysqldb']
      {%- endif -%}
    state: present

- name: 'Search for gitea stateless password'
  set_fact:
    gitea_db_password: >-
      {%- set gitea_db_password_list = play_hosts|map('extract', hostvars,
              ['gitea_config', 'database', 'PASSWD'])|select|list -%}
      {%- if gitea_db_password_list|length > 0 -%}
          {{ gitea_db_password_list|first }}
      {%- else -%}
          {{ lookup('password', '/dev/null') }}
      {%- endif -%}
  when: gitea_dn_password is undefined

- name: 'update gitea config'
  set_fact:
    gitea_config: >-
      {%- set database_dict = gitea_config.setdefault('database', {}) -%}
      {%- set _ = database_dict.update({
        'DB_TYPE': 'mysql',
        'HOST': gitea_mariadb.instance.endpoint ~ ':3306',
        'USER': gitea_db_username,
        'PASSWD': gitea_db_password,
        'NAME': gitea_db_name,
      }) -%}
      {{ gitea_config }}

- debug:
    var: gitea_config
  when: debug|bool

- name: 'create gitea password for mariadb'
  mysql_user:
    login_host: '{{ gitea_mariadb.instance.endpoint }}'
    login_user: '{{ db_username }}'
    login_password: '{{ db_password }}'
    host: '%'
    name: '{{ gitea_db_username }}'
    password: '{{ gitea_config.database.PASSWD }}'
