- name: 'install python binding for mariadb'
  package:
    name: >-
      {%- if ansible_python.version.major == 3 -%}
         ['python3-mysqldb']
      {%- else -%}
         ['python-mysqldb']
      {%- endif -%}
    state: present

- name: 'create gitea password for mariadb'
  mysql_user:
    login_host: '{{ gitea_mariadb.instance.endpoint }}'
    login_user: '{{ db_username }}'
    login_password: '{{ db_password }}'
    host: '%'
    name: '{{ gitea_db_username }}'
    password: '{{ _gitea_db_password }}'
